### ISSUE TITLE
ui: clear asynchronous tasks in useEffect

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-ui#122]
After signing in into the application I get this error in the console:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Signin (at App.js:61)
    in Route (at App.js:59)
    in Switch (at App.js:58)
```

**Comment by audrium** [comment]
I traced it back to this [line](https://github.com/reanahub/reana-ui/blob/master/reana-ui/src/pages/signin/Signin.js#L42). After user info is fetched in `Signin` component, React Router redirects to `WorkflowList`, but `Signin` component still tries to update its state with `setFormData`. Also, it seems that `history.replace` is not needed?

**Comment by mvidalgarcia** [comment]
`history.replace` is a mechanism to remember the URL the user was trying to access. For instance, if I'm not logged in and I access something like `https://reana.cern.ch/details/bb7cfdc5-16f2-4c94-ae9b-325e96761cdb`, then I'm properly redirected to this page after a successful sign-in.

As you correctly stated, the issue is that `setFormData` is called to wipe the password in case the sign-in failed, and this is performed even though the sign is was successful and thus redirected to the `from` page. So if we wrapped this call in an `else` so be enough to avoid this no-op.

```diff
diff --git a/reana-ui/src/pages/signin/Signin.js b/reana-ui/src/pages/signin/Signin.js
index e54a827..083dce3 100644
--- a/reana-ui/src/pages/signin/Signin.js
+++ b/reana-ui/src/pages/signin/Signin.js
@@ -36,10 +36,12 @@ export default function Signin({ signup }) {
   const handleSubmit = (event, action) => {
     const { from } = location.state || { from: { pathname: "/" } };
     dispatch(action(formData)).then((res) => {
       if (res.ok) {
         history.replace(from);
+      } else {
+        setFormData({ ...formData, password: "" });
       }
-      setFormData({ ...formData, password: "" });
     });
     event.preventDefault();
   };
```
