### ISSUE TITLE
quotas: create mock up

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-ui#128]
Create mockups on how to meaningfully show user quotas in REANA-UI. To take into account:
- Should it go in "Your profile" or be a dedicated dashboard?
- Amendments to home page
  - Add notifications, e.g. 90%+ quota usage reached
  - Filter workflow list
  - Show consumption per workflow?
- Aggregate quota usage of all runs of a specific workflow e.g. demohelloworld.1, demohelloworld.2, demohelloworld.3 etc...
- ...

More details on which exact information will be displayed will come from https://github.com/reanahub/reana-db/issues/83, however, we can "mock" it for the time being having a look to what other systems show.

**Comment by mvidalgarcia** [comment]
> Should it go in "Your profile" or be a dedicated dashboard?

IMO it depends on the amount of information we are going to display (and how). If it's just the current total CPU and HDD usage and its limits, it can proably go in "Your profile". If we're going to display a more elaborate dashboard with a workflow breakdown, plots and so on, perhaps it's worth having a new page.
One approach could be starting in the "Your profile" page, and if it grows too much eventually move it to a new page.

> - Filter workflow list

Do you mean based on some specific quota criteria?

> - Aggregate quota usage of all runs of a specific workflow e.g. demohelloworld.1, demohelloworld.2, demohelloworld.3 etc...

So far we display runs as separate items in the workflow list page, should we aggregate runs of the same workflow in a unique item? Perhaps it can display the number of runs and be collapsable? This way we can show the total quota usage and the breakdown of each run when expanded.

**Comment by tiborsimko** [comment]
WRT dashboard, could be a simply pie chart like diagram 0->100% to see where people are, for each resource.  (Starting cpu and disk only.) Bonus points for making pie chart composed of several runs, e.g. all bsm runs in blue, all roofit runs in yellow, etc.  (This is probably outside of MVP due to other live logs coming tasks. So let's start simple.)

WRT filtering, we can revive your old mock-ups to show only finished workflows, only bsm workflows... and, if we add quota display to workflow list, then we could filter on disk usage or cpu usage"find me all workflows that have disk usage more than 10GB" or something. However, the latter might be better served via search facets, which that would be another big offside topic, so we could stay with simple filters, matching use case such as: "list all finished workflows,  order by oldest, see the size, and click on "delete" button in R/W if I don't need them, in order to liberate my disk size quota).

WRT aggregation, this was an idea just for the user quota dashboard page, e.g. the pie chart mentioned above. (And it is probably beyond MVP anyway.) No need to modify workflow list page at this stage, I think...

**Comment by mvidalgarcia** [comment]
> WRT dashboard, could be a simple set of pie chart like diagrams showing 0->100% progress, to see where people are, for each resource. (Starting cpu and disk only.) 

![profile (quotas)](https://user-images.githubusercontent.com/8863238/94158868-2dc0c380-fe83-11ea-9656-e3a3e37c402e.png)


> so we could stay with simple filters, matching use case such as: "list all finished workflows, order by oldest, see the size, and click on "delete" button in R/W if I don't need them, in order to liberate my disk size quota).

![image](https://user-images.githubusercontent.com/8863238/94162350-e63c3680-fe86-11ea-81f5-e2049748944d.png)

**Comment by mvidalgarcia** [comment]
I think we can close this issue and split in two:
- Display "Your quota" in the profile page
- Implement filtering in workflow list page

If we want to make design changes, they can be done during the implementation phase.

**Comment by mvidalgarcia** [comment]
Issues created:
- https://github.com/reanahub/reana-ui/issues/132
- https://github.com/reanahub/reana-ui/issues/133
