### ISSUE TITLE
ui: quota notifications, e.g. 90%+ quota usage reached

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-ui#160]
The idea here is to display some notifications in the UI part when a certain percentage of usage is reached. This way we can keep the user informed and they can free some disk by deleting old workflows.

We can also consider sending emails when reaching certain limits.

**Comment by tiborsimko** [comment]
We do have disk quota usage numbers displayed in the "Your profile" page, but that is a bit hidden.

It would be good to display a small teaser right on the home page for better awareness, e.g. as people may know about it from Google services:

![disk-warning](https://user-images.githubusercontent.com/517546/169248588-cfbaf0ab-c7b8-471a-8e4d-e8765bb8c1ff.png)

We could similarly display a gentle teaser on the workflow list page that would show above certain threshold and that would guide the user to a page explaining what to do (sort workflows by most-disk-space-used, delete unneeded ones, set up shorter retention periods for unneeded files, etc).

P.S. The email sending shouldn't be necessary for MVP. If we introduce stricter disk quotas, users would be prevented from launching new workflows, and would be guided to this info page, so that they would create "lighter workflows" progressively.  

(Although email warning might be good to add later for GitLab <-> REANA bridge users who don't necessarily see the REANA home page so often.)
