### ISSUE TITLE
cluster health: position of the emoticon

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#315]
A cosmetic UI issue.

(1) In the page footer, on any page, we have menu emoticons shown on the left of text:

![health-1](https://user-images.githubusercontent.com/517546/234311384-30bc2376-2865-4d76-ac8f-49661045b7f2.png)

In the cluster health page title, we have the emoticon shown on the right of text:

![health-2](https://user-images.githubusercontent.com/517546/234311623-18133cb3-b3d8-43eb-9529-b8ed516b3391.png)

It would be nice to harmonise this and e.g. always shown emoticon on the left of the text.

(2) If we choose to use emoticons, we could invent one for "Your workflows" that currently does not have any:

![health-3](https://user-images.githubusercontent.com/517546/234312034-0d1bea1d-f12d-4f64-b805-9e58173ef476.png)

Ditto for the personal pages such as:

![health-4](https://user-images.githubusercontent.com/517546/234312328-1435ba3c-5cf6-4126-875a-74de71fafeed.png)

Alternatively to adding new emoticons, we can actually drop the one from the Cluster Health page title, to have title without emoticons everywhere. (And keep emoticons only in the page footer.)

(3) Note also the US English capitalisation of titles "Cluster Health" and "Privacy Notice" vs  British English capitalisation of titles "Your workflows", "Your profile", "Your quota", etc.  Since we usually use BrE over AmE, let's harmonise titles to only use capital letter for the first word of a page title. (I.e. change the current text to have "Cluster health", "Privacy notice", etc.)

**Comment by giuseppe-steduto** [comment]
I like the idea of adding emoticons to the titles.

I tried to find a few possibly suitable emoticons in the React Semantic UI package, from which the other icons are taken, both for design consistency and to not add more dependencies.
For the personal page we could use, respectively, the `key`, `gitlab` and `circle notch` icons. The result would be similar to this:
![image](https://user-images.githubusercontent.com/34663336/235692284-7355bfdc-e0a5-4cb5-b7c6-789ad4b4eb93.png)

Finding an emoticon for "Your workflows" title in the Semantic UI icon catalog was a bit harder. One idea could be to use the `list` one, referring to the fact that this section is a list of the dispatched workflows:
![image](https://user-images.githubusercontent.com/34663336/235696243-1922b509-4659-415e-8959-48c453417764.png)
A more "creative" approach could be to use the `fork` icon, but upside down, recalling the idea of two parallel workflow steps that are spawned from the parent step:
![image](https://user-images.githubusercontent.com/34663336/235696339-9676c437-dd9a-41f4-a7da-c83525094d2b.png)

**Comment by tiborsimko** [comment]
@giuseppe-steduto If we go the emoticon way, can you please look through all the other exposed web pages such as https://reana.cern.ch/launch and find suitable leading emojis for them?

**Comment by giuseppe-steduto** [comment]
### Launch on REANA
For this I think the `rocket` icon is the right choice, since it's also consistent with the one on the "Launch" button
![image](https://user-images.githubusercontent.com/34663336/236168763-fb629243-289e-456a-ba77-51a79f3e542a.png)

### Cern Privacy Notice
For this one, IMO we could either choose `secret user`,
![image](https://user-images.githubusercontent.com/34663336/236170914-c20cbeb3-40fc-46b5-a69c-fbb3fea5b784.png)


the `book` one, giving its look a more formal/legal appearance,
![image](https://user-images.githubusercontent.com/34663336/236169240-6927548f-37cc-4fd6-9c8c-9dfc22bd520a.png)

but maybe the best choice is using the `privacy` icon (which is an alias for the `key` icon), as it's also the one used in the privacy policy link in the footer
![image](https://user-images.githubusercontent.com/34663336/236173971-07b422ea-3071-4922-a89e-ee35bdf77865.png)

 
Also, in general, I don't think we should add emoticons/icons to the titles that are smaller than H2 (like the "how is your data used" one)

### Welcome to REANA
This is the title that the users get on the home page, when they haven't started any workflows yet.
I didn't find very suitable emoticons for this in the Semantic UI catalog, but maybe one amongst `group`, `check`, or a generic one like `star` or `gem` will do:
![image](https://user-images.githubusercontent.com/34663336/236184864-7261d597-3ee3-4a0d-8d0d-d164aa582eb0.png)



### Alternative - use Unicode emojis
We could also not rely on the Semantic UI `Icon` component, but rather use the unicode emojis directly as text 🔑📊🧑‍💻. The results would be similar to these:
![image](https://user-images.githubusercontent.com/34663336/236183001-c4806d35-43bb-4b89-8864-8d3e601e93f7.png)
It may look nice, but maybe it's a bit too humorous or inconsistent with the rest of the design. We can discuss.

**Comment by mdonadoni** [comment]
I personally (weakly) prefer not having emoticons anywhere, thus dropping the one in the "Cluster health" page.

However, if we decide to add icons everywhere, I would then avoid color emojis and I would suggest:
- `tachometer alternate` or `pie chart` for "Your quota"
    
    ![](https://user-images.githubusercontent.com/13397702/236838520-8371503b-8598-4507-a379-75c394866be9.png) ![](https://user-images.githubusercontent.com/13397702/236839018-62cb3ef5-37ee-4358-b141-be8c3427a029.png)

-  I like the `fork` icon for "Your workflows", but an alternative could be `flask`

    ![](https://user-images.githubusercontent.com/13397702/236839345-4a90500c-fdae-4e42-95af-0f668f31d014.png)

- `star` is the one I like the most for "Welcome to REANA" among the ones proposed
- Regarding "Privacy notice", I would avoid `book` (already used for docs) and `key` (already used for the REANA token). Other than `secret user`, we could also use `shield` or `lock`

    ![](https://user-images.githubusercontent.com/13397702/236843180-c5a981e4-60e2-4716-976f-f7bb026c4e7e.png) ![](https://user-images.githubusercontent.com/13397702/236843094-81829976-65b6-4d7c-858d-592446b023ff.png)
