### ISSUE TITLE
preview: better whitelist/blacklist 

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-ui#79]
Currently, the Workspace file previewer doesn't allow to preview `.root` files, but it allows previewing `.exe` files, which is obviously not functional and better be avoided.

Let's improve whitelisting/blacklisting formats which are good for preview and which are forbidden from being previewed.

Pay attention to security, XSS and friends.

I'd say let's rather blacklist everything by default and allow previewing only good formats (`.py`, `.C`, `.png`, etc) rather than whitelisting everything by default (leading to the above `.exe` file problem.)

P.S. In the future, we could implement proper MIME type detection and such; this is about fixing current status quickly.

**Comment by mvidalgarcia** [comment]
Just for the record, to inform what the current situation is.

At the moment, the [r-w-c download endpoint](https://github.com/reanahub/reana-workflow-controller/blob/dc33bf212dd282518cfd27dbaad0f9af426f889d/reana_workflow_controller/rest/workflows_workspace.py#L235-L238) is serving files by default as `multipart/form-data` so that can be downloaded unless they are images, then are served as mime-type `image/*` to allow direct preview from the server. This check is uniquely based on file name at the moment so it's not very robust as one could upload an executable file changing its extension to `.jpg` and the server would serve it as previewable.

If this issue is just about whitelisting by default this is done at the [client level](https://github.com/reanahub/reana-ui/blob/master/reana-ui/src/pages/workflowDetails/components/WorkflowFiles.js#L32-L33) and can be easily tackled. We would then need the list of:

- Server previewable files: Files that can be previewed directly from the server e.g images, pdf, etc.
- Client previewable files: Files whose content can be downloaded from server and displayed in the UI: `plain/text` files basically (Action: to find an npm library that guesses the mime-type based on file name to whitelist)

The rest of files can **only** be downloaded and not previewed.

As mentioned in the issue description, in the future we can implement a more robust way of mime-type detection based on file content instead of file name, and performed mainly on the server side.

**Comment by mvidalgarcia** [comment]
Checking some npm packages:

### [mime](https://www.npmjs.com/package/mime)

```js
mime.getType("hello.exe")
"application/octet-stream"
mime.getType("hello.jpeg")
"image/jpeg"
mime.getType("hello.jpg")
"image/jpeg"
mime.getType("hello.png")
"image/png"
mime.getType("hello.pdf")
"application/pdf"
mime.getType("hello.c")
"text/x-c"
mime.getType("hello.py")
null
mime.getType("hello.js")
"application/javascript"
mime.getType("hello.java")
"text/x-java-source"
mime.getType("hello.cpp")
"text/x-c"
mime.getType("hello.root")
null
mime.getType("hello.C")
"text/x-c"
mime.getType("hello.json")
"application/json"
mime.getType("hello.yaml")
"text/yaml"
```
### [mime-types](https://www.npmjs.com/package/mime-types)

```js
mime.lookup("hello.exe")
"application/x-msdos-program"
mime.lookup("hello.jpeg")
"image/jpeg"
mime.lookup("hello.jpg")
"image/jpeg"
mime.lookup("hello.png")
"image/png"
mime.lookup("hello.pdf")
"application/pdf"
mime.lookup("hello.c")
"text/x-c"
mime.lookup("hello.C")
"text/x-c"
mime.lookup("hello.py")
false
mime.lookup("hello.js")
"application/javascript"
mime.lookup("hello.java")
"text/x-java-source"
mime.lookup("hello.cpp")
"text/x-c"
mime.lookup("hello.css")
"text/css"
mime.lookup("hello.root")
false
mime.lookup("hello.json")
"application/json"
mime.lookup("hello.yaml")
"text/yaml"
```

For some reason Python files are not being detected as `text/` so this is bad for us.
